In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
import numpy as np
zeros_arr = np.zeros((3, 3), dtype=int)
print(zeros_arr)
ones_arr = np.ones((2, 2), dtype=int)
print(ones_arr)

arrange_arr = np.arange(10)
print(arrange_arr)
#array manipulation
reshaped_arr = arr.reshape(5,1)
print(reshaped_arr)
sliced_arr = arr[2:4]
print(sliced_arr)
a=np.array([1,2,3,4,5,6,7,8])
b =a.T
print(b)
b=np.split(a,4)
print(b)



[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1]
 [1 1]]
[0 1 2 3 4 5 6 7 8 9]
[[1]
 [2]
 [3]
 [4]
 [5]]
[3 4]
[1 2 3 4 5 6 7 8]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c=np.dot(a,b)
print(c)
d = np.linalg.eig(c)
print(d)


[[19 22]
 [43 50]]
EigResult(eigenvalues=array([5.80198014e-02, 6.89419802e+01]), eigenvectors=array([[-0.75781077, -0.40313049],
       [ 0.65247439, -0.91514251]]))


In [22]:
data = np.loadtxt("/content/drive/MyDrive/dataset/bro.txt",dtype=int)
d = np.savetxt("/content/drive/MyDrive/dataset/bro.txt.txt",data)
print(d)
print(data)

None
[[1 2 3 4 5]
 [6 7 8 9 0]]


In [29]:
arr=np.arange(0,100,5)
print(arr)
data=np.savetxt("/content/arr.txt",arr)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [61]:

a =np.random.rand()
print(a)
b=np.random.randint(0,2)
print(b)
c=np.array([[1,2],[3,4]])
print(c.max(axis=0))
print(c.ndim)
print(c.shape)

0.8081374375733622
0
[3 4]
2
(2, 2)


In [66]:
a=np.array([2,3,5,6,7,8])
print(a.resize(3,2))
print(a.cumsum())
print(a.shape)
print(a.cumsum())


None
[ 2  5 10 16 23 31]
(3, 2)
[ 2  5 10 16 23 31]


In [39]:
a=np.linspace(0.8,2,5)
print(a)
b=np.arange(24).reshape(3,2,4)
print(b)

[0.8 1.1 1.4 1.7 2. ]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [42]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.dot(a,b))
print(a@(b))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [60]:
from numpy import random
a=np.ones((2,3),dtype=int)
print(a.max(axis=0))
print(a.sum(axis=1))
print(a.sum(axis=0))

[1 1 1]
[3 3]
[2 2 2]


In [56]:
a=np.ceil(np.random.random((2,12)))
print(a)
c=np.random.random((2,2))
print(c)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0.08919746 0.17812474]
 [0.62146161 0.60465158]]


In [78]:
a=np.array([2,3,5,6,7,8])
print(a.resize(2,3))
b=np.array([9,10,1,2,3,4])
print(b.resize(2,3))
print(np.vstack((a,b)))
print(np.hstack((a,b)))

None
None
[[ 2  3  5]
 [ 6  7  8]
 [ 9 10  1]
 [ 2  3  4]]
[[ 2  3  5  9 10  1]
 [ 6  7  8  2  3  4]]


In [77]:
b=np.arange(30).reshape(2,3,5)
print(b)
print(np.dstack(b))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


no.of rows become
no.of colums become                               
group become column


In [10]:
a1=np.eye(4)
print(a1)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
x = [1,2,3]
a = np.array(x)
print (a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [8]:
x =np.array([1, 4, 0], float)
y =np.array([2, 2, 1], float)
print(np.inner(x, y))
print(np.outer(x, y))
print(np.cross(x, y))

10.0
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
[ 4. -1. -6.]


In [24]:
g=np.array([[15,55,65],[85,95,78]])
h=np.array([[45,85,75],[15,10,65]])
print(np.union1d(g,h))

print(np.intersect1d(g,h))

print(np.setdiff1d(g,h))

a=np.array([[10,21,50,2,25,25]])
b=np.array([[10,21,50,2,25,25]])
c=np.divmod(a,b)
print(c)

print(np.divide(a,b))

print(np.multiply(a,b))

[10 15 45 55 65 75 78 85 95]
[15 65 85]
[55 78 95]
(array([[1, 1, 1, 1, 1, 1]]), array([[0, 0, 0, 0, 0, 0]]))
[[1. 1. 1. 1. 1. 1.]]
[[ 100  441 2500    4  625  625]]


In [34]:
from numpy import random
x=random.normal(size=(2,3))
print(x)
print(" ")
x=random.normal(loc=1,scale=2,size=(2,3))
print(x)
print(" ")
x=random.binomial(n=12,p=0.5,size=10)
print(x)

x=random.choice([3,5])
print(x)
print(" ")
x=random.choice([3,5],p=[0.2,0.8],size=(3,5))
print(x)

[[-2.75371721  0.5726552  -0.86789736]
 [ 1.0726399  -0.28783794 -1.14318526]]
 
[[ 3.998204    1.37203131 -2.64640802]
 [ 1.2922352  -0.83101712  1.34567988]]
 
[9 8 7 5 6 6 8 4 9 5]
3
 
[[5 3 5 5 3]
 [5 5 5 5 5]
 [5 5 5 3 5]]
